### ISSUE TITLE
Error dont Load the newest Version

### ISSUE THREAD

**Issue by editon96** [HoshiKurama/TicketManager-Bridge-Releases#1]
Hey I use Velocity 3.2.1-snapshot Build 207 and get that Error [https://mclo.gs/hi0zvbd](url)

So it dont Load at start and crash. I dongarte back and hope you can fix that.

Thank you!
If you need more Infos say a word!

**Comment by HoshiKurama** [comment]
I identified an issue that will be patched in the next update. Sorry for the inconvenience!

**Comment by HoshiKurama** [comment]
Fixed with 2.0

**Comment by editon96** [comment]
Thank you!
